import tables

const
  # see also ruby-roo lib at: http://github.com/hmcgowan/roo
  FORMATS* = {
      "general": "float",
      "0": "float",
      "0.00": "float",
      "#,##0": "float",
      "#,##0.00": "float",
      "0%": "percentage",
      "0.00%": "percentage",
      "0.00e+00": "float",
      "mm-dd-yy": "date",
      "d-mmm-yy": "date",
      "d-mmm": "date",
      "mmm-yy": "date",
      "h:mm am/pm": "date",
      "h:mm:ss am/pm": "date",
      "h:mm": "time",
      "h:mm:ss": "time",
      "m/d/yy h:mm": "date",
      "#,##0 ;(#,##0)": "float",
      "#,##0 ;[red](#,##0)": "float",
      "#,##0.00;(#,##0.00)": "float",
      "#,##0.00;[red](#,##0.00)": "float",
      "mm:ss": "time",
      "[h]:mm:ss": "time",
      "mmss.0": "time",
      "##0.0e+0": "float",
      "@": "float",
      "yyyy\\-mm\\-dd": "date",
      "dd/mm/yy": "date",
      "hh:mm:ss": "time",
      "dd/mm/yy\\ hh:mm": "date",
      "dd/mm/yyyy hh:mm:ss": "date",
      "yy-mm-dd": "date",
      "d-mmm-yyyy": "date",
      "m/d/yy": "date",
      "m/d/yyyy": "date",
      "dd-mmm-yyyy": "date",
      "dd/mm/yyyy": "date",
      "mm/dd/yy h:mm am/pm": "date",
      "mm/dd/yy hh:mm": "date",
      "mm/dd/yyyy h:mm am/pm": "date",
      "mm/dd/yyyy hh:mm:ss": "date",
      "yyyy-mm-dd hh:mm:ss": "date",
      "#,##0;(#,##0)": "float",
      "_(* #,##0_);_(* (#,##0);_(* \"-\"??_);_(@_)": "float",
      "_(* #,##0.00_);_(* (#,##0.00);_(* \"-\"??_);_(@_)": "float"
  }.toTable

  STANDARD_FORMATS* = {
      "0": "general",
      "1": "0",
      "2": "0.00",
      "3": "#,##0",
      "4": "#,##0.00",
      "9": "0%",
      "10": "0.00%",
      "11": "0.00e+00",
      "12": "# ?/?",
      "13": "# ??/??",
      "14": "mm-dd-yy",
      "15": "d-mmm-yy",
      "16": "d-mmm",
      "17": "mmm-yy",
      "18": "h:mm am/pm",
      "19": "h:mm:ss am/pm",
      "20": "h:mm",
      "21": "h:mm:ss",
      "22": "m/d/yy h:mm",
      "37": "#,##0 ;(#,##0)",
      "38": "#,##0 ;[red](#,##0)",
      "39": "#,##0.00;(#,##0.00)",
      "40": "#,##0.00;[red](#,##0.00)",
      "45": "mm:ss",
      "46": "[h]:mm:ss",
      "47": "mmss.0",
      "48": "##0.0e+0",
      "49": "@",
  }.toTable
  
